### ISSUE TITLE
Import module issue

### ISSUE THREAD

**Issue by rezanatorr** [sonofeft/RocketCEA#11]
Hi,

I have been attempting to import and run one of the examples from the rocketcea site. However I receive these errors, I'm not sure if it is a problem from my side or if there is an issue with the DLL file. 

Thanks!

### py script:

1   ##-----------import modules----------##
2   import numpy as np
3   import scipy
4   from scipy.integrate import odeint
5   import matplotlib.pyplot as plt
6   import CoolProp.CoolProp as clp
7   from CoolProp.CoolProp import PropsSI
8   import cantera as ct
9   **import rocketcea as CEA**
10 **from rocketcea.cea_obj import CEA_Obj**
11 ##-----------------------------------##
12 
13 **C = CEA.cea_obj(oxName='LOX', fuelName='LH2')**
14 

### Output:
ImportError                               Traceback (most recent call last)
~\anaconda3\envs\Toolbox\lib\site-packages\rocketcea\cea_obj.py in <module>
     51 try:
---> 52     import rocketcea.py_cea as py_cea
     53 except:

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-5-a0f2f296cceb> in <module>
      8 import cantera as ct
      9 import rocketcea as NASA_CEA
---> 10 from rocketcea.cea_obj_w_units import CEA_Obj
     11 ##-----------------------------------##
     12 

~\anaconda3\envs\Toolbox\lib\site-packages\rocketcea\cea_obj_w_units.py in <module>
      4 
      5 
----> 6 from rocketcea.cea_obj import CEA_Obj as CEA_Obj_default
      7 from rocketcea.units import get_units_obj
      8 

~\anaconda3\envs\Toolbox\lib\site-packages\rocketcea\cea_obj.py in <module>
     58     else:
     59         # go ahead and raise the error.
---> 60         import rocketcea.py_cea as py_cea
     61 
     62 

ImportError: DLL load failed: The specified module could not be found.

**Comment by pnp-peeyush** [comment]
How did you resolve the issue?? I'm having the exact same trouble! Please help a brother out...

**Comment by rezanatorr** [comment]
> How did you resolve the issue?? I'm having the exact same trouble! Please help a brother out...

Hi,

Yes I did fix it, my silly mistake - because I was using Anaconda I was installing everything through that and in actually fact I did not have Python installed 🤦‍♂️

So double check that you have Python 3.8 installed on your computer and that there is a PATH in your SYSTEM directory to it.

**Comment by pnp-peeyush** [comment]
Yes I already had python 3.8 and path was also added, I've just confirmed this as well. The problem is still there.

**Comment by giovaniceotto** [comment]
Had a very similar issue. When running the following line:

`python -c "from rocketcea.cea_obj import CEA_Obj; C=CEA_Obj(oxName='LOX', fuelName='LH2'); print(C.get_Isp())"`

I got this error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\%USERNAME%\miniconda3\lib\site-packages\rocketcea\cea_obj.py", line 51, in <module>
    import rocketcea.py_cea as py_cea
ImportError: DLL load failed: The specified module could not be found.
```

Turns out the dll which was missing was the one inside rocketcea\.libs folder. In my case, it is named libpy_cea.VUR565GUPPPERV2WK3S72H5RZXS56EK5.gfortran-win_amd64.dll.

I moved it out of the .libs folder and placed it simply in the rocketcea folder. Worked as expected.

Not really sure if this is a bug in Windows or if it's just my computer.

**Comment by sonofeft** [comment]
Thanks for posting a fix.

Can you describe for me how you installed RocketCEA and the platform you are on?

A number of people have had trouble on Windows with python 3.8 and I have not been able to solve the problem.

In the digging I have done, it seems as if python 3.8 has implemented some security features with regard to loading DLL files and the file you found in the .lib directory looks like it has been digitally signed with a hash of some kind.

It sounds like you are on Windows, using python 3.8 with Anaconda and in that environment, a .lib folder gets created when MinGW is run. I assume you either did a pip install or a conda install.

Can you describe the details.

Thanks,

Charlie

**Comment by giovaniceotto** [comment]
Sure! Here are my platform specifications:

**OS**

- Windows 10 Build 19041.388

**Python Environment - Conda with Python 3.7.7** 

- active environment : base
- active env location : C:\Users\Giovani\miniconda3
- shell level : 1
- user config file : C:\Users\Giovani\.condarc
- populated config files :
- conda version : 4.8.3
- conda-build version : not installed
- python version : 3.7.7.final.0
- virtual packages : __cuda=9.1
- base environment : C:\Users\Giovani\miniconda3  (writable)
- channel URLs : 
   * https://repo.anaconda.com/pkgs/main/win-64
   * https://repo.anaconda.com/pkgs/main/noarch
   * https://repo.anaconda.com/pkgs/r/win-64
   * https://repo.anaconda.com/pkgs/r/noarch
   * https://repo.anaconda.com/pkgs/msys2/win-64
   * https://repo.anaconda.com/pkgs/msys2/noarch
- package cache 
   * C:\Users\Giovani\miniconda3\pkgs
   * C:\Users\Giovani\.conda\pkgs
   * C:\Users\Giovani\AppData\Local\conda\conda\pkgs
- envs directories 
   * C:\Users\Giovani\miniconda3\envs
   * C:\Users\Giovani\.conda\envs
   * C:\Users\Giovani\AppData\Local\conda\conda\envs
- platform : win-64
- user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Windows/10 Windows/10.0.19041
- administrator : False
- netrc file : None
- offline mode : False

**Installation Method**

- `pip install rocketcea`
- Compiler: gfortran at C:\Program Files\Mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin
- Also had to install Microsoft Visual C++ Build Tools

I actually found the problem when inspecting the process monitor. After executing the line of code to import rocketcea, the following `NAME NOT FOUND` errors occurred:

![image](https://user-images.githubusercontent.com/572483/88821143-aa436880-d198-11ea-8a30-98aef73d2d9c.png)

You can see the DLL named `libpy_cea.VUR565GUPPPERV2WK3S72H5RZXS56EK5.gfortran-win_amd64.dll` can't be found because the /.libs/ folder is not being searched.

**Comment by sonofeft** [comment]
Although RocketCEA does not currently support python 3.8, it's clear I need to reopen this issue and put out a new version that does support python 3.8.

**Comment by sonofeft** [comment]
Thanks again for submitting your setup... I thought the problem was just with python 3.8, however, your 3.7.7 indicates otherwise.
Perhaps the issue is a "pip" upgrade issue... I have some work ahead of me.

**Comment by sonofeft** [comment]
For python 3.8 64 bit on Windows, the "DLL load failed" message appears to be referring to "libgcc_s_seh-1.dll" and "libquadmath-0.dll"

This can be fixed by either adding the new "os.add_dll_directory" command to cea_obj.py or by copying the DLL files into the rocketcea directory where the py_cea_cp38-win_amd64.pyd file resides.

In my case I added: 
>   os.add_dll_directory( r'C:\MinGW\mingw64\bin' ) 
to cea_obj.py since my MinGw DLL files are there.

Note that 32 bit python 3.8 on Windows has bigger problems that I have not yet figured out. I will leave this issue open until I get some positive user feedback.  

I also need to figure out how to handle the os.add_dll_directory in a generic way for all users. 
(i.e. I don't want to bundle the dll files with RockeCEA)

**Comment by sonofeft** [comment]
When I compile RockeCEA on Windows for python 3.7 64 bit, I use the following batch file.
The batch file makes the PATH as simple as possible so that only the 64 bit MinGW files are found
Note that it also uninstalls rocketcea in case bad files are left from previous attempts.
You will need to edit the hard-coded paths to your own location of python and MinGW.
Give it a try and let me know.

rem =============== RUN_SETUP_BUILD_WIN64.BAT ================
rem set python path variable (Default is Python 3.7 64 bit)
IF "%1"=="" ( SET "MYPYTHONPATH=D:\Python37_64" ) ELSE ( SET "MYPYTHONPATH=D:\Python%1_64" )

rem Make sure that PATH is as simple as possible
set PATH=C:\MinGW\mingw64\bin;C:\MinGW\mingw64\lib;%MYPYTHONPATH%;%MYPYTHONPATH%\Scripts

pip uninstall -y rocketcea

python setup.py build --compiler=mingw32

python setup.py install
python setup.py sdist bdist_wheel

rem Test the compiled module
python -c "from rocketcea.cea_obj import CEA_Obj; C=CEA_Obj(oxName='LOX', fuelName='LH2'); print(C.get_Isp())"

**Comment by sonofeft** [comment]
I've just updated the docs for a Windows batch file that seems to work for python 3.8 and 3.9.
see: https://rocketcea.readthedocs.io/en/latest/quickstart.html#windows-batch-file
It uses  "Unofficial Windows Binaries for Python Extension Packages" to solve the dependency compile issues.

**Comment by Ahorvath94** [comment]
Hi there,

System Info:
Windows 10
Python 3.8

I tried installing MinGW 32 bit on a separate windows 10 computer running Python 3.8. I ran the batch file you have above, but I still get "no module named 'rocketcea.py_cea". When you run it, is there a py_cea.pyd file that is supposed to be output? In the rocketcea folder, I have py_cea.f, py_cea.inc, py_cea.pyf, and on my other computer in the same folder I have py_cea.cp37-win_amd64 and py_cea.o. I am working through it but just curious as to what the actual file extension should be.

Thanks!

Alex

**Comment by RubenvdBerg** [comment]
Same issues on Windows 10 tested with fresh installs of python 3.7, 3.8 and, 3.9. with and without the batch file. Still get the following error:

```
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\rocketcea\cea_obj.py", line 59, in <module>
    import rocketcea.py_cea as py_cea
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\rocketcea\cea_obj.py", line 67, in <module>
    import rocketcea.py_cea as py_cea
ImportError: DLL load failed: The specified module could not be found.
```

Would love if you could get it to a stable version for windows. I'm doing my thesis work on Linux and there it works absolutely fine, but having rocketcea as a dependency for my own modules, forces everyone that wants to use/extend it to Linux as well.

Don't want to sound demanding. A fix for windows would be much appreciated, but I absolutely love the package either way :). Thanks a lot for your work!

**Comment by sonofeft** [comment]
Sorry for the long delay fixing the Windows issue. 
I will marshal all my courage and try again.
If you discover a fix before I do, please let me know.

**Comment by RubenvdBerg** [comment]
Thank you for looking into it again, but don't feel pressured. I'll let you know if I do

**Comment by sonofeft** [comment]
Install for 64 bit python 3.9 on Windows 10 should be working now.
(32 bit python 3.8 and above does not.)

Download "mingw-w64-install.exe" from: 
https://sourceforge.net/projects/mingw-w64/

Install MinGW using instructions at:
https://rocketcea.readthedocs.io/en/latest/installgfortran.html#windows-10
  
Install RockeCEA using instructions at:
https://rocketcea.readthedocs.io/en/latest/quickstart.html#windows-batch-file
  
I tested the above approach today on a clean Windows 10 installation and it worked with 64 bit python 3.9
If you have problems, let me know

**Comment by RubenvdBerg** [comment]
Tried it for Python 3.9, Windows 1o 64-bit and it worked for me! Very much appreciated you fixed it this quickly, thanks a ton!

**Comment by Sinsha30** [comment]
Worked super well for me too as I encountered the same issue! Thank you! Tested with Python3.11 and Windows 11
